# Generated by Django 3.0.4 on 2020-04-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
